version: "3"
services:
  oqt-workers:
    container_name: oqt-workers
    build:
      context: ./
    env_file:
      - development.env
    environment:
      - OHSOME_API="https://api.ohsome.org/v1/"
    command: uvicorn ohsome_quality_tool.app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"
    ports:
      - 8000:8000

  oqt-database:
    container_name: oqt-database
    build:
      context: database/
      dockerfile: development.Dockerfile
    ports:
      - "5435:5432"
    volumes:
      - oqt-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - development.env

  oqt-website:
    container_name: oqt-website
    build:
      context: website
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./website/website:/usr/share/nginx/html

    volumes:
      - oqt-data
