version: "3"
services:
  oqt-workers:
    container_name: oqt-workers
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      OHSOME_API: 'https://api.ohsome.org/v1/'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'hexadmin'
      POSTGRES_DB: 'hexadmin'
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
    command: uvicorn ohsome_quality_tool.api:app --host 0.0.0.0 --port 8000 --reload
    restart: "unless-stopped"
    ports:
      - "8080:8000"
    volumes:
      - oqt-website:/root/.local/share/ohsome_quality_tool/data
    networks:
      - oqt-network
      - oqt-website-network

  oqt-database:
    container_name: oqt-database
    build:
      context: database/
      dockerfile: Dockerfile.development
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'hexadmin'
      POSTGRES_DB: 'hexadmin'
    restart: "unless-stopped"
    ports:
      - "5435:5432"
    volumes:
      - oqt-data:/var/lib/postgresql/data
    networks:
      - oqt-network

  oqt-website:
    container_name: oqt-website
    build:
      context: website/
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - ./website/website:/usr/share/nginx/html
      - oqt-website:/usr/share/nginx/html/data
    networks:
      - oqt-website-network

networks:
  oqt-network:
  oqt-website-network:

volumes:
  oqt-data:
  oqt-website:
