version: "3"
networks:
  oqt-network:

services:
  oqt-workers:
    container_name: oqt-workers
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      OHSOME_API: 'https://api.ohsome.org/v1/'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'hexadmin'
      POSTGRES_DB: 'hexadmin'
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 'oqt-database'
    command: uvicorn ohsome_quality_tool.app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - oqt-website:/root/.local/share/ohsome_quality_tool/data
    networks:
      - oqt-network

  oqt-database:
    container_name: oqt-database
    build:
      context: database/
      dockerfile: Dockerfile.development
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'hexadmin'
      POSTGRES_DB: 'hexadmin'
    restart: "always"
    ports:
      - "5435:5432"
    volumes:
      - oqt-data:/var/lib/postgresql/data
    networks:
      - oqt-network

  oqt-website:
    container_name: oqt-website
    build:
      context: website/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./website/website:/usr/share/nginx/html
      - oqt-website:/usr/share/nginx/html/data

volumes:
  oqt-data: {}
  oqt-website: {}
