version: "3"
services:
  oqt-workers:
    container_name: oqt-workers
    build:
      context: ./
    env_file:
      - ./.env
    environment:
      - OHSOME_API="https://api.ohsome.org/v1/"
    command: uvicorn ohsome_quality_tool.app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"
    ports:
      - 8000:8000

  oqt-postgres:
    container_name: oqt-postgres
    build:
      context: ohsome_hex_db/
      dockerfile: Dockerfile.dev
    ports:
      - "5435:5432"
    volumes:
      - ./oqt-db-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data

  oqt-website:
    container_name: oqt-website
    build:
      context: website
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./website/website:/usr/share/nginx/html


