version: "3.8"
services:
  db:
    build:
      context: ohsome_hex_db/
    ports:
      - "5432:5432"
    volumes:
      - ohsome_hex_db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD: "hzTZJ"
