version: "3.3"
services:
  oqt-workers:
    build:
      context: ./
    environment:
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
      - POSTGRES_USER='${POSTGRES_USER}'
      - POSTGRES_DB='${POSTGRES_DB}'
      - POSTGRES_HOST='postgres'
      - POSTGRES_PORT=5432
      - OHSOME_API='https://api.ohsome.org/v1/'
    command: uvicorn ohsome_quality_tool.app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"
    ports:
      - 8000:8000

  #oqt-db:
  #  build:
  #    context: ohsome_hex_db/
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - ohsome_hex_db_data:/var/lib/postgresql/data
  #  restart: always
  #  environment:
  #    - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
  #    - POSTGRES_USER='${POSTGRES_USER}'
      # - POSTGIS_ENABLE_OUTDB_RASTERS: 1
      # - POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
