version: "3.8"
services:
  db:
    build:
      context: database/
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
    # environment:
      # POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      # POSTGRES_USER: '${POSTGRES_USER}'
      # POSTGRES_DB: '${POSTGRES_DB}'
      # PGDATA: '/var/lib/postgresql/data/ohsome-hex'
