[tool.poetry]
name = "ohsome-quality-tool"
version = "0.1.0"
description = ""
authors = ["Matthias Schaub <schaub@stud.uni-heidelberg.de>"]

[tool.poetry.dependencies]
python = "^3.8"
pre-commit = "^2.8.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
Black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
