version: 1
formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(filename)s - %(funcName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
  file:
    backupCount: 14
    class: logging.handlers.TimedRotatingFileHandler
    filename: '%(logfilepath)s'
    formatter: standard
    interval: 1
    when: D
root:
  handlers:
  - console
  - file
  level: '%(level)s'
