[tool.poetry]
name = "ohsome_quality_analyst"
version = "0.2.0"
description = "Intrinsic and extrinsic data quality metrics for OpenStreetMap data."
authors = [
  "Benjamin Herfort <Benjamin.Herfort@heigit.org>",
  "Fabian Kowatsch <Fabian.Kowatsch@heigit.org>",
  "Jochen Stier <Jochen.Stier@heigit.org>",
  "Johannes Visintini <Johannes.Visintini@heigit.org>",
  "Katharina Przybill <Katharina.Przybill@heigit.org>",
  "Matthias Schaub <Matthias.Schaub@heigit.org>",
  "Mohammed Rizwan Khan <rizwan@uni-heidelberg.de>",

  ]
homepage = "https://oqt.ohsome.org"
repository = "https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/apps/ohsome-quality-analyst/"
keywords = [
  "osm",
  "gis",
  "geography",
  "metric",
  "ohsome",
  "quality",
  ]

[tool.poetry.dependencies]
python = "^3.8"
geojson = "^2.5.0"
click = "^7.1.2"
fastapi = "^0.61.2"
uvicorn = "^0.12.2"
requests = "^2.25.0"
matplotlib = "^3.2.2"
pandas = "^1.1.5"
dacite = "^1.6.0"
PyYAML = "^5.4.1"
toml = "^0.10.2"
httpx = "^0.17.0"
asyncpg = "^0.22.0"

[tool.poetry.dev-dependencies]
flake8 = "3.8.4"
Black = "20.8b1"
mypy = "0.790"
pre-commit = "^2.10.0"
schema = "^0.7.3"
pytest = "^6.2.2"
isort = "5.7.0"

[tool.poetry.scripts]
oqt = "ohsome_quality_analyst.cli:cli"

[tool.poetry.urls]
"Issues" = "https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/apps/ohsome-quality-analyst/-/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
